// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Usamos el operador de propagación (...) para meter la propiedad 'url'
    // únicamente si process.env.DATABASE_URL contiene un texto.
    ...(process.env['DATABASE_URL']
      ? { url: process.env['DATABASE_URL'] }
      : {}),
  },
});
